# BestROM versioning
BESTROM_VERSION := 1.0
BESTROM_BUILD_DATE := $(shell date -u +%Y%m%d)
BESTROM_BUILD_TYPE ?= UNOFFICIAL

ifeq ($(BESTROM_BUILD_TYPE),OFFICIAL)
  BESTROM_BUILD_VARIANT := OFFICIAL
else
  BESTROM_BUILD_VARIANT := UNOFFICIAL
endif

BESTROM_DISPLAY_VERSION := $(BESTROM_VERSION)-$(BESTROM_BUILD_VARIANT)-$(BESTROM_BUILD_DATE)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    ro.bestrom.version=$(BESTROM_VERSION) \
    ro.bestrom.display.version=$(BESTROM_DISPLAY_VERSION) \
    ro.bestrom.build.type=$(BESTROM_BUILD_VARIANT) \
    ro.bestrom.device=$(TARGET_DEVICE)
